---
- name: Install Python3 from source
  hosts: 127.0.0.1
  gather_facts: false
  become_user: root
  tasks:
  - name: try become methods
    command: whoami
    register: out
  - debug: var=out.stdout_lines
  - name: Install Python
    become_user: root
    apt: name={{ item }}
    with_items:
      - python3
      - python3-pip

