---
- name: pythonSetup
  hosts: localhost
  remote_user: root
  tasks:
  - name: Install Python
    apt-get: name={{ item }} state=present force_apt_get=yes
    with_items:
      - python3
      - python3-pip
    become: true

