---
- name: pythonSetup
  hosts: localhost
  remote_user: root
  
  tasks: 
  -name: try become methods
   command: whoami
  - name: Install Python
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items: 
    - python3
    - python3-pip
    become: true
