---
- name: try become methods
  hosts: localhost 
  become: yes
  become_user: "root"
  become_method: su
  #command: whoami
  
- name: pythonSetup
  hosts: localhost
  remote_user: root
  
  tasks: 
  - name: Install Python
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items: 
    - python3
    - python3-pip
    become: true
