---
- name: pythonSetup
  hosts: 127.0.0.1
  tasks: 
  - name: Install Python
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items: 
    - python3
    - python3-pip
    become: true
