---
- name: pythonSetup
  hosts: 127.0.0.1
  tasks: 
  - name: Update APT 
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: true

  - name: Install Python
    apt: name={{ item }} update_cache=true state=present force_apt_get=yes
    with_items: 
    - python3
    - python3-pip
    become: true
