---
- name: Install Python3 from source
  hosts: 127.0.0.1
  become: yes
  tasks:
  - name: Install Python
    apt: name={{ item }} state=present force_apt_get=yes
    with_items:
      - python3
      - python3-pip

