---
- name: Install Python3 from source
  hosts: 127.0.0.1
  gather_facts: false
  become: yes
  tasks:
  - name: Install Python
    become_user: root
    apt: name={{ item }}
    with_items:
      - python3
      - python3-pip

